# Generated by Django 6.0.2 on 2026-02-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktier',
            name='ticker',
            field=models.CharField(max_length=12),
        ),
    ]
