# Generated by Django 6.0.2 on 2026-02-09 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_aktier_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='aktiepriser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DateField()),
                ('pris_close', models.FloatField()),
                ('selskab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.aktier')),
            ],
        ),
    ]
