# Generated by Django 6.0.2 on 2026-02-11 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_aktiepriser'),
    ]

    operations = [
        migrations.CreateModel(
            name='nyheder_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('site', models.CharField(max_length=100)),
                ('titel', models.CharField(max_length=200)),
                ('tekst', models.TextField()),
                ('selskab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.aktier')),
            ],
        ),
    ]
