# Generated by Django 6.0.2 on 2026-02-11 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_nyheder_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='ai_news_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('nyheds_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selskab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.aktier')),
            ],
        ),
    ]
