# Generated by Django 6.0.2 on 2026-02-11 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_ai_news_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato_fra', models.DateField()),
                ('dato_til', models.DateField()),
                ('annotation_text', models.TextField()),
                ('selskab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.aktier')),
            ],
        ),
    ]
