# Generated by Django 6.0.2 on 2026-02-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='dato_til',
            field=models.DateField(blank=True, null=True),
        ),
    ]
