# Generated by Django 6.0.2 on 2026-02-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_annotation_dato_til'),
    ]

    operations = [
        migrations.CreateModel(
            name='debat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bruger', models.CharField(max_length=100)),
                ('tekst', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selskab', models.ManyToManyField(to='stocks.aktier')),
            ],
        ),
    ]
