# Generated by Django 6.0.2 on 2026-02-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_debat'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='tidsperiode',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
