# Generated by Django 6.0.2 on 2026-02-13 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_annotation_tidsperiode'),
    ]

    operations = [
        migrations.CreateModel(
            name='kursmål',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DateField()),
                ('kursmål_pris', models.FloatField()),
                ('anbefaling', models.CharField(max_length=20)),
                ('analytiker', models.CharField(max_length=100)),
                ('kommentar', models.TextField(blank=True)),
                ('selskab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.aktier')),
            ],
        ),
    ]
