# Generated by Django 6.0.2 on 2026-02-13 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_kursmål'),
    ]

    operations = [
        migrations.AddField(
            model_name='nyheder_links',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
