# Generated by Django 6.0.2 on 2026-02-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_nyheder_links_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_news_summary',
            name='words_highlighted_list',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='forced_y_position',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
