# Generated by Django 6.0.2 on 2026-02-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_ai_news_summary_words_highlighted_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotation_text',
            field=models.CharField(max_length=200),
        ),
    ]
