# Generated by Django 6.0.2 on 2026-02-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_alter_annotation_annotation_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kursmål',
            new_name='kursmaal',
        ),
    ]
