# Generated by Django 6.0.2 on 2026-02-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_rename_kursmål_kursmaal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kursmaal',
            old_name='kursmål_pris',
            new_name='kursmaal_pris',
        ),
    ]
