# Generated by Django 6.0.2 on 2026-02-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_rename_kursmål_pris_kursmaal_kursmaal_pris'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='pris_paa_dato_fra',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
