# Generated by Django 6.0.2 on 2026-02-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_annotation_pris_paa_dato_fra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotation_text',
            field=models.TextField(max_length=140),
        ),
    ]
