# Generated by Django 6.0.2 on 2026-03-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_alter_annotation_annotation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktier',
            name='paavirkningsfaktorer',
            field=models.TextField(blank=True),
        ),
    ]
